### ISSUE TITLE
Remove package-metadata.json

### ISSUE THREAD

**Issue by wbond** [Stuk/sublime-edit-history#1]
This file is automatically generated by Package Control when installing the plugin and is used to track the currently installed version.

If you are looking to explicitly version your package, you'll need to create a custom packages.json file like https://raw.github.com/timonwong/sublime_packages/master/packages.json. If you do that, just be sure to specify a tag the download URL so that everyone who has the same version number is running the same code. If you specify master as the download URL and commit a change, but don't update the packages.json file then it could start getting confusing in terms of knowing what version of code a user is running.

**Comment by Stuk** [comment]
Removed, I was just copying the other packages I had installed :) Thanks very much!
