### ISSUE TITLE
ST3 compatibility

### ISSUE THREAD

**Issue by vojtajina** [Stuk/sublime-edit-history#10]
This is a great plugin. Would be awesome to get it compatible with Sublime Text 3.

**Comment by Stuk** [comment]
I think this functionality is included in Sublime Text 3, based on "Jump Back and Jump Forward" in this blog post: http://www.sublimetext.com/blog/articles/sublime-text-3-beta-3019

I haven't tried ST3 out yet, so I'm not sure how it compares?

**Comment by vojtajina** [comment]
@Stuk you are right. I didn't know that. That's awesome, this plugin was really helpful so I'm not surprised it made it to the core...

**Comment by Stuk** [comment]
Glad you found it helpful while it was needed :D

**Comment by Stuk** [comment]
I'm actually still using ST2, so have not given it a go. I'm afraid I'm not going to have much time to look at it in the near future. If you want to take a look, that would be great!
